scrape_configs:
  # Monitor Docker container metrics (CPU/Memory/Network)
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']  # Docker's built-in metrics endpoint
    labels:
      service: 'static-site-container'

  # Monitor site uptime (Blackbox Exporter)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Checks if HTTP 200 OK
    static_configs:
      - targets:
          - http://localhost:8888  # Your container's exposed port
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Blackbox exporter running on host
